// Generated by gencpp from file uvc/enable.msg
// DO NOT EDIT!


#ifndef UVC_MESSAGE_ENABLE_H
#define UVC_MESSAGE_ENABLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uvc
{
template <class ContainerAllocator>
struct enable_
{
  typedef enable_<ContainerAllocator> Type;

  enable_()
    : enable(false)  {
    }
  enable_(const ContainerAllocator& _alloc)
    : enable(false)  {
  (void)_alloc;
    }



   typedef uint8_t _enable_type;
  _enable_type enable;





  typedef boost::shared_ptr< ::uvc::enable_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uvc::enable_<ContainerAllocator> const> ConstPtr;

}; // struct enable_

typedef ::uvc::enable_<std::allocator<void> > enable;

typedef boost::shared_ptr< ::uvc::enable > enablePtr;
typedef boost::shared_ptr< ::uvc::enable const> enableConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uvc::enable_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uvc::enable_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uvc::enable_<ContainerAllocator1> & lhs, const ::uvc::enable_<ContainerAllocator2> & rhs)
{
  return lhs.enable == rhs.enable;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uvc::enable_<ContainerAllocator1> & lhs, const ::uvc::enable_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uvc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::uvc::enable_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uvc::enable_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uvc::enable_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uvc::enable_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uvc::enable_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uvc::enable_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uvc::enable_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c1211af706069c994c06e00eb59ac9e";
  }

  static const char* value(const ::uvc::enable_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c1211af706069c9ULL;
  static const uint64_t static_value2 = 0x94c06e00eb59ac9eULL;
};

template<class ContainerAllocator>
struct DataType< ::uvc::enable_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uvc/enable";
  }

  static const char* value(const ::uvc::enable_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uvc::enable_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool enable\n"
;
  }

  static const char* value(const ::uvc::enable_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uvc::enable_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct enable_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uvc::enable_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uvc::enable_<ContainerAllocator>& v)
  {
    s << indent << "enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UVC_MESSAGE_ENABLE_H
