// Generated by gencpp from file uvc/set_enableResponse.msg
// DO NOT EDIT!


#ifndef UVC_MESSAGE_SET_ENABLERESPONSE_H
#define UVC_MESSAGE_SET_ENABLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uvc
{
template <class ContainerAllocator>
struct set_enableResponse_
{
  typedef set_enableResponse_<ContainerAllocator> Type;

  set_enableResponse_()
    : status(false)  {
    }
  set_enableResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::uvc::set_enableResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uvc::set_enableResponse_<ContainerAllocator> const> ConstPtr;

}; // struct set_enableResponse_

typedef ::uvc::set_enableResponse_<std::allocator<void> > set_enableResponse;

typedef boost::shared_ptr< ::uvc::set_enableResponse > set_enableResponsePtr;
typedef boost::shared_ptr< ::uvc::set_enableResponse const> set_enableResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uvc::set_enableResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uvc::set_enableResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uvc::set_enableResponse_<ContainerAllocator1> & lhs, const ::uvc::set_enableResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uvc::set_enableResponse_<ContainerAllocator1> & lhs, const ::uvc::set_enableResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uvc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::uvc::set_enableResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uvc::set_enableResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uvc::set_enableResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uvc::set_enableResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uvc::set_enableResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uvc::set_enableResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uvc::set_enableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::uvc::set_enableResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::uvc::set_enableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uvc/set_enableResponse";
  }

  static const char* value(const ::uvc::set_enableResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uvc::set_enableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
"\n"
;
  }

  static const char* value(const ::uvc::set_enableResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uvc::set_enableResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_enableResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uvc::set_enableResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uvc::set_enableResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UVC_MESSAGE_SET_ENABLERESPONSE_H
