// Generated by gencpp from file uvc/set_lampRequest.msg
// DO NOT EDIT!


#ifndef UVC_MESSAGE_SET_LAMPREQUEST_H
#define UVC_MESSAGE_SET_LAMPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uvc
{
template <class ContainerAllocator>
struct set_lampRequest_
{
  typedef set_lampRequest_<ContainerAllocator> Type;

  set_lampRequest_()
    : active(false)  {
    }
  set_lampRequest_(const ContainerAllocator& _alloc)
    : active(false)  {
  (void)_alloc;
    }



   typedef uint8_t _active_type;
  _active_type active;





  typedef boost::shared_ptr< ::uvc::set_lampRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uvc::set_lampRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_lampRequest_

typedef ::uvc::set_lampRequest_<std::allocator<void> > set_lampRequest;

typedef boost::shared_ptr< ::uvc::set_lampRequest > set_lampRequestPtr;
typedef boost::shared_ptr< ::uvc::set_lampRequest const> set_lampRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uvc::set_lampRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uvc::set_lampRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uvc::set_lampRequest_<ContainerAllocator1> & lhs, const ::uvc::set_lampRequest_<ContainerAllocator2> & rhs)
{
  return lhs.active == rhs.active;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uvc::set_lampRequest_<ContainerAllocator1> & lhs, const ::uvc::set_lampRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uvc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::uvc::set_lampRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uvc::set_lampRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uvc::set_lampRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uvc::set_lampRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uvc::set_lampRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uvc::set_lampRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uvc::set_lampRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c5cfb0a2565df41de6873994aee57d2";
  }

  static const char* value(const ::uvc::set_lampRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c5cfb0a2565df41ULL;
  static const uint64_t static_value2 = 0xde6873994aee57d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::uvc::set_lampRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uvc/set_lampRequest";
  }

  static const char* value(const ::uvc::set_lampRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uvc::set_lampRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool active\n"
;
  }

  static const char* value(const ::uvc::set_lampRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uvc::set_lampRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.active);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_lampRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uvc::set_lampRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uvc::set_lampRequest_<ContainerAllocator>& v)
  {
    s << indent << "active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.active);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UVC_MESSAGE_SET_LAMPREQUEST_H
