// Generated by gencpp from file uvc/set_enable.msg
// DO NOT EDIT!


#ifndef UVC_MESSAGE_SET_ENABLE_H
#define UVC_MESSAGE_SET_ENABLE_H

#include <ros/service_traits.h>


#include <uvc/set_enableRequest.h>
#include <uvc/set_enableResponse.h>


namespace uvc
{

struct set_enable
{

typedef set_enableRequest Request;
typedef set_enableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_enable
} // namespace uvc


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uvc::set_enable > {
  static const char* value()
  {
    return "d459cf8faf2747a90df40f12140e9b9c";
  }

  static const char* value(const ::uvc::set_enable&) { return value(); }
};

template<>
struct DataType< ::uvc::set_enable > {
  static const char* value()
  {
    return "uvc/set_enable";
  }

  static const char* value(const ::uvc::set_enable&) { return value(); }
};


// service_traits::MD5Sum< ::uvc::set_enableRequest> should match
// service_traits::MD5Sum< ::uvc::set_enable >
template<>
struct MD5Sum< ::uvc::set_enableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uvc::set_enable >::value();
  }
  static const char* value(const ::uvc::set_enableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uvc::set_enableRequest> should match
// service_traits::DataType< ::uvc::set_enable >
template<>
struct DataType< ::uvc::set_enableRequest>
{
  static const char* value()
  {
    return DataType< ::uvc::set_enable >::value();
  }
  static const char* value(const ::uvc::set_enableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uvc::set_enableResponse> should match
// service_traits::MD5Sum< ::uvc::set_enable >
template<>
struct MD5Sum< ::uvc::set_enableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uvc::set_enable >::value();
  }
  static const char* value(const ::uvc::set_enableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uvc::set_enableResponse> should match
// service_traits::DataType< ::uvc::set_enable >
template<>
struct DataType< ::uvc::set_enableResponse>
{
  static const char* value()
  {
    return DataType< ::uvc::set_enable >::value();
  }
  static const char* value(const ::uvc::set_enableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UVC_MESSAGE_SET_ENABLE_H
