(cl:defpackage uvc-srv
  (:use )
  (:export
   "SET_ENABLE"
   "<SET_ENABLE-REQUEST>"
   "SET_ENABLE-REQUEST"
   "<SET_ENABLE-RESPONSE>"
   "SET_ENABLE-RESPONSE"
   "SET_LAMP"
   "<SET_LAMP-REQUEST>"
   "SET_LAMP-REQUEST"
   "<SET_LAMP-RESPONSE>"
   "SET_LAMP-RESPONSE"
  ))

